### ISSUE TITLE
angular 9 : Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by bakai-dev** [crystalui/angular-lightbox#10]
angular 9
version pro lightbox_v1.1.2

in mobile error Cannot read property 'nativeElement' of undefined
I tried to add
@ViewChild('content', {static: true}) contentElement: ElementRef;
the error in the console disappeared, but the animation does not work correctly

`ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at PinchZoomComponent.ngOnInit (pinch-zoom.component.ts:95)
    at callHook (core.js:4735)
    at callHooks (core.js:4699)
    at executeInitAndCheckHooks (core.js:4639)
    at selectIndexInternal (core.js:9701)
    at Module.ɵɵadvance (core.js:9662)
    at LightboxTouchscreenComponent_Template (lightbox-touchscreen.component.html:24)
    at executeTemplate (core.js:12098)
    at refreshView (core.js:11945)
    at refreshComponent (core.js:13410)`

**Comment by drozhzhin-n-e** [comment]
@BakayDev Thank you for reporting, I will fix it. Could you explain in more detail what the animation means does not work correctly?

Try to remove the margin from the body, I think this can solve the problem with the animation:
```
body {
    margin: 0;
}
```

**Comment by bakai-dev** [comment]
in the normal version, without an increase, everything works well,
![Screenshot_20200507_131941](https://user-images.githubusercontent.com/13073820/81266278-537d3580-9066-11ea-876f-068f80162d9c.png)

with increase pro version - 
after clicking on the image, the photo does not increase when closing when you click the animation again, there’s no just a circle around the image everything turns black

![Screenshot_20200507_132232](https://user-images.githubusercontent.com/13073820/81266390-7e678980-9066-11ea-9629-46b52476161b.png)

and after clicking the close button everything freezes
![Screenshot_20200507_132359](https://user-images.githubusercontent.com/13073820/81266460-92ab8680-9066-11ea-8154-2596f90d6cc2.png)

**Comment by drozhzhin-n-e** [comment]
@BakayDev Do you get errors in the console during the opening or closing of the lightbox?

**Comment by BakayDev** [comment]
@drozhzhin-n-e  no errors on  console 
I will show you the video you can watch https://youtu.be/-BBkHCLgZxs

**Comment by bakai-dev** [comment]
@drozhzhin-n-e 
everything works fine on the regular version  import {CrystalLightboxModule} from '@crystalui/angular-lightbox';
but about the version, make a mistake about the video
 
I shot a new video, I hope you will get a better understanding, I detected an error as it appeared you can see on the video https://youtu.be/kDO-EOKS16M
error on console
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by drozhzhin-n-e** [comment]
@BakayDev Ok, I see. I apologize, apparently I did not check the mobile version after the last changes. I will try to fix this within 24 hours.

**Comment by bakai-dev** [comment]
@drozhzhin-n-e ok, thank you

**Comment by drozhzhin-n-e** [comment]
@BakayDev I published version 1.1.3, it has a fix for this problem. You can download it from the same link in the email.

**Comment by bakai-dev** [comment]
@drozhzhin-n-e  everything works fine, thank you
