### ISSUE TITLE
Not working in Chrome responsive view tool

### ISSUE THREAD

**Issue by rushenn** [crystalui/angular-lightbox#3]
Gallery is not working when tried to preview within Chrome's responsive view tool. It fires the following error when clicked on the image.

`ERROR TypeError: Cannot read property 'nativeElement' of undefined`

I'm not sure wether this related to the plugin or Chrome itself.

**Comment by drozhzhin-n-e** [comment]
@rushenn  Does the error occur in your application or here http://crystalui.org/components/lightbox?

**Comment by rushenn** [comment]
@drozhzhin-n-e It seems like the error is in my application which is built on Angular7.

**Comment by drozhzhin-n-e** [comment]
@rushenn Can you see in which file and in which line this error occurs?

**Comment by rushenn** [comment]
@drozhzhin-n-e https://byrushan.com/projects/material-admin/app/2.6.1/angular/#/photo-gallery Please take a look

**Comment by drozhzhin-n-e** [comment]
@rushenn This is a compiled project with minified code. Could you see the project in development mode (`ng serve`)?

**Comment by rushenn** [comment]
@drozhzhin-n-e Okay, will check it out and let you know.

**Comment by rushenn** [comment]
@drozhzhin-n-e Let me know if you need any further information

<img width="1248" alt="Screen Shot 2019-04-02 at 14 28 35" src="https://user-images.githubusercontent.com/13393018/55389879-ba6f1780-5553-11e9-9b54-59cb5eb8fdb5.png">

**Comment by drozhzhin-n-e** [comment]
@rushenn OK. I will try to fix it soon.

**Comment by rushenn** [comment]
@drozhzhin-n-e Thank you

**Comment by drozhzhin-n-e** [comment]
@rushenn try version 1.0.6

**Comment by rushenn** [comment]
@drozhzhin-n-e Thank you
