### ISSUE TITLE
Preserve not changed properties on any property change

### ISSUE THREAD

**Issue by ilianiv** [crystalui/angular-lightbox#4]
If a property binding gets changed all other properties get lost :(

Example:
```ts
counter: boolean = true;
separator: string = ' of ';
```
```html
<img [src]="image.path" height="150" lightbox [counter]="counter" [counterSeparator]="separator" />
<button (click)="counter = !counter">Toggle counter</button>
```

When `counter` changes `counterSeparator` will be lost because lightbox's properties will be replaced with changes from ngOnChanges() but only `counter` was changed so `counterSeparator` is missing in changes object.   
See https://github.com/crystalui/angular-lightbox/blob/master/projects/crystalui/angular-lightbox/src/lib/lightbox.directive.ts#L79

**Comment by drozhzhin-n-e** [comment]
@ilianiv thank!
